config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resource :session, only: %i[create destroy]
    resource :user, only: %i[show update]
    resources :tomatoes, only: %i[index show create update destroy]
    resources :projects, only: %i[index show create update destroy]

    namespace :leaderboard do
      resource :daily, only: :show
      resource :weekly, only: :show
      resource :monthly, only: :show
      resource :overall, only: :show
    end
  end

  resources :tags, only: :index
  get '/tags/*id', to: 'tags#show', format: false, as: :tag

  resources :projects

  resources :statistics, only: :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  namespace :leaderboard do
    resource :daily, only: :show
    resource :weekly, only: :show
    resource :monthly, only: :show
    resource :overall, only: :show
  end

  resources :tomatoes

  resources :users, only: %i[show edit update destroy] do
    resources :tomatoes, only: [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin/:provider' => 'sessions#new', as: :signin
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/auth/failure' => 'sessions#failure'

  root to: 'welcome#index'

end

app/controllers/api/leaderboard/base_controller.rb
module Api
  module Leaderboard
    class BaseController < Api::BaseController
      include LeaderboardController

      def show
        render json: Presenter::Scores.new(@scores)
      end
    end
  end
end

app/controllers/api/leaderboard/dailies_controller.rb
module Api
  module Leaderboard
    class DailiesController < Api::Leaderboard::BaseController
      include LeaderboardController

      private

      def scope
        DailyScore.scoped
      end
    end
  end
end

app/controllers/api/leaderboard/monthlies_controller.rb
module Api
  module Leaderboard
    class MonthliesController < Api::Leaderboard::BaseController
      include LeaderboardController

      private

      def scope
        MonthlyScore.scoped
      end
    end
  end
end

app/controllers/api/leaderboard/overalls_controller.rb
module Api
  module Leaderboard
    class OverallsController < Api::Leaderboard::BaseController
      include LeaderboardController

      private

      def scope
        OverallScore.scoped
      end
    end
  end
end

app/controllers/api/leaderboard/weeklies_controller.rb
module Api
  module Leaderboard
    class WeekliesController < Api::Leaderboard::BaseController
      include LeaderboardController

      private

      def scope
        WeeklyScore.scoped
      end
    end
  end
end

app/controllers/concerns/leaderboard_controller.rb
module LeaderboardController
  extend ActiveSupport::Concern

  included do
    before_action :find_scores, only: :show
  end

  def show; end

  def find_scores
    @scores = scope.includes(:user).desc(:score).page(params[:page])
  end
end

app/controllers/leaderboard/dailies_controller.rb
module Leaderboard
  class DailiesController < ApplicationController
    include LeaderboardController

    private

    def scope
      DailyScore.scoped
    end
  end
end

app/controllers/leaderboard/monthlies_controller.rb
module Leaderboard
  class MonthliesController < ApplicationController
    include LeaderboardController

    private

    def scope
      MonthlyScore.scoped
    end
  end
end

app/controllers/leaderboard/overalls_controller.rb
module Leaderboard
  class OverallsController < ApplicationController
    include LeaderboardController

    private

    def scope
      OverallScore.scoped
    end
  end
end

app/controllers/leaderboard/weeklies_controller.rb
module Leaderboard
  class WeekliesController < ApplicationController
    include LeaderboardController

    private

    def scope
      WeeklyScore.scoped
    end
  end
end

app/views/leaderboard/_leaderboard.html.erb
<% unless scores.empty? %>
  <ol class="media-list" start="<%= (25*(params[:page].to_i-1))+1 if params[:page] %>">
    <% scores.each_with_index do |item, index| %>
      <% if item.user %>
        <li class="media <%= content_for_user(item.user) { 'you' } %>">
          <p><em><%= ((25 * ((params[:page] || 1).to_i - 1)) + index + 1).ordinalize %></em></p>
          <div class="profile_image media-left">
            <%= profile_image(item.user, 36, class: 'media-object') %>
          </div>
          <div class="profile_info media-body">
            <h4 class="media-heading"><%= user_name(item.user) %></h4>
            <p><%= item.score.to_i %> <%= Tomato.model_name.human(count: item.score.to_i).downcase %></p>
          </div>
        </li>
      <% end %>
    <% end %>
  </ol>

  <%= paginate scores %>
<% else %>
  <p><%= t('empty_leaderboard') %></p>
<% end %>

app/views/leaderboard/_links.html.erb
<%= t('leaderboards') %>:
<%= link_to t('daily'), leaderboard_daily_path %>,
<%= link_to t('weekly'), leaderboard_weekly_path %>,
<%= link_to t('monthly'), leaderboard_monthly_path %>,
<%= link_to t('overall'), leaderboard_overall_path %>