config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resource :session, only: %i[create destroy]
    resource :user, only: %i[show update]
    resources :tomatoes, only: %i[index show create update destroy]
    resources :projects, only: %i[index show create update destroy]

    namespace :leaderboard do
      resource :daily, only: :show
      resource :weekly, only: :show
      resource :monthly, only: :show
      resource :overall, only: :show
    end
  end

  resources :tags, only: :index
  get '/tags/*id', to: 'tags#show', format: false, as: :tag

  resources :projects

  resources :statistics, only: :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  namespace :leaderboard do
    resource :daily, only: :show
    resource :weekly, only: :show
    resource :monthly, only: :show
    resource :overall, only: :show
  end

  resources :tomatoes

  resources :users, only: %i[show edit update destroy] do
    resources :tomatoes, only: [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin/:provider' => 'sessions#new', as: :signin
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/auth/failure' => 'sessions#failure'

  root to: 'welcome#index'

end

app/views/shared/_ad_unit.html.erb
<!-- Tomatoes responsive -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7194529311513014"
     data-ad-slot="1689770271"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/shared/_announcement.html.erb
<% if ENV['ANNOUNCEMENT'] %>
  <div id="announcement" class="well well-sm">
    <h4><%= t('announcement') %></h4>
    <p><%= raw(ENV['ANNOUNCEMENT']) %></p>
  </div>
<% end %>

app/views/shared/_fb.html.erb
<script>(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
  var fbds = document.createElement('script');
  fbds.async = true;
  fbds.src = '//connect.facebook.net/en_US/fbds.js';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(fbds, s);
  _fbq.loaded = true;
}
_fbq.push(['addPixelId', '1469176326651099']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" border="0" alt="" style="display:none" src="https://www.facebook.com/tr?id=1469176326651099&amp;ev=NoScript" /></noscript>

app/views/shared/_flash.html.erb
<% flash.each do |key, msg| %>
  <div class="alert <%= flash_class(key) %>"><p><%= msg %></p></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p class="support-tomatoes">
          <%= t('footer.support_the_project_html') %>
        </p>
        <p>
          <%= render partial: 'leaderboard/links' %><br/>
          <%= link_to "API Reference", page_path('api_reference') %>,
          <%= link_to "How to", page_path('how_to') %>,
          <%= link_to "Statistics", statistics_path %><br/>
          <%= link_to "Terms of service", page_path('terms') %>,
          <%= link_to "Privacy policy", page_path('privacy') %>,
          <%= link_to "Imprint", page_path('imprint') %>
        </p>
      </div>
      <div class="col-md-6">
        <p>
          <%= t('footer.follow_updates_html') %><br/>
          <%= t('footer.join_chat_html') %><br/>
          <%= link_to t('app_name'), TomatoesApp::REPO %> - <%= link_to "version #{TomatoesApp::VERSION}", "#{TomatoesApp::REPO}/tree/#{TomatoesApp::VERSION}" %>
        </p>
        <div id="add_to_chrome">
          <p>
            <%= link_to 'https://chrome.google.com/webstore/detail/jijbhneeenepenoolcdalnekggeialeo' do %>
              <i class="fa fa-chrome" aria-hidden="true"></i> <%= t('footer.add_to_chrome') %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p class="trademarks">
          <%= t('footer.disclaimer_html') %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_ga.html.erb
<%= javascript_tag do %>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2935139-19']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('app_name'), root_path, class: 'navbar-brand logo' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= user_name(current_user) %></li>
          <li><%= link_to t('sign_out'), signout_path, method: :delete %></li>
        <% else %>
          <li>
            <%= link_to signin_path(Authorization::PROVIDER_GITHUB), method: :post do %>
              <%= image_tag('github.png', width: 24) %>
              <%= t('signin_with.github') %>
            <% end %>
          </li>
          <li>
            <%= link_to signin_path(Authorization::PROVIDER_TWITTER), method: :post do %>
              <%= image_tag('twitter.png', width: 24) %>
              <%= t('signin_with.twitter') %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_public_header.html.erb
<header class="public">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><%= link_to t('app_name'), root_path, class: 'logo' %></h1>
        <h3><%= t('description_html') %></h3>
      </div>
    </div>
  </div>
</header>