config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resource :session, only: %i[create destroy]
    resource :user, only: %i[show update]
    resources :tomatoes, only: %i[index show create update destroy]
    resources :projects, only: %i[index show create update destroy]

    namespace :leaderboard do
      resource :daily, only: :show
      resource :weekly, only: :show
      resource :monthly, only: :show
      resource :overall, only: :show
    end
  end

  resources :tags, only: :index
  get '/tags/*id', to: 'tags#show', format: false, as: :tag

  resources :projects

  resources :statistics, only: :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  namespace :leaderboard do
    resource :daily, only: :show
    resource :weekly, only: :show
    resource :monthly, only: :show
    resource :overall, only: :show
  end

  resources :tomatoes

  resources :users, only: %i[show edit update destroy] do
    resources :tomatoes, only: [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin/:provider' => 'sessions#new', as: :signin
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/auth/failure' => 'sessions#failure'

  root to: 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

  before_action :new_tomato, if: :current_user
  before_action :daily_tomatoes, if: :current_user
  before_action :tomatoes_counters, if: :current_user
  before_action :daily_projects, if: :current_user

  def index; end

  private

  def new_tomato
    @tomato = current_user.tomatoes.build
  end

  # rubocop:disable Naming/MemoizedInstanceVariableName
  def daily_tomatoes
    @tomatoes ||= current_user.tomatoes.after(Time.zone.now.beginning_of_day)
                              .order_by([%i[created_at desc]])
  end
  # rubocop:enable Naming/MemoizedInstanceVariableName

  def tomatoes_counters
    @tomatoes_count = current_user.tomatoes_counters
  end

  def daily_projects
    @projects = daily_tomatoes.collect(&:projects).flatten.uniq
  end
end

app/views/welcome/_dashboard.html.erb
<div class="row">
  <div class="col-md-6">
    <div id="tomatoes_list">
      <%= render partial: 'tomatoes_list', locals: {high: nil} %>
    </div>
    <div id="projects_list">
      <%= render partial: 'projects_list' %>
    </div>
  </div>

  <div class="col-md-6">
    <div id="user_statistics">
      <%= render partial: 'user_statistics' %>
    </div>
  </div>
</div>

app/views/welcome/_projects_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to t('welcome.today_s_projects'), projects_path %></h3>
  </div>
  <% if @projects.empty? %>
    <div class="panel-body">
      <p><%= t('welcome.no_projects_yet_html', new_project_link: link_to(t('project.new').downcase, new_project_path) ) %></p>
    </div>
  <% end %>
  <% unless @projects.empty? %>
    <table class="table">
      <%= render partial: 'projects/project', collection: @projects %>
    </table>
  <% end %>
</div>

app/views/welcome/_tomatoes_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to t('welcome.today_s_tomatoes'), tomatoes_path %></h3>
  </div>
  <% if @tomatoes.empty? %>
    <div class="panel-body">
      <p><%= t('welcome.no_tomatoes_yet_html') %></p>
    </div>
  <% end %>
  <% unless @tomatoes.empty? %>
    <table class="table">
      <%= render partial: 'tomatoes/tomato', collection: @tomatoes, locals: {high: high} %>
    </table>
  <% end %>
</div>

app/views/welcome/_tomatoes_timer.html.erb
<% content_for :scripts do %>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/soundmanager2/2.97a.20150601/script/soundmanager2-nodebug-jsmin.js"
    integrity="sha256-5KBL+8gS3BkWOs22YOrezN3Djl4pwodgZaPQY9hgu4Y="
    crossorigin="anonymous"></script>

  <%= javascript_tag do %>
    <%= render partial: 'welcome/timer/configuration.js' %>
    <%= render partial: 'welcome/timer/translations.js' %>
  <% end %>

  <%= javascript_include_tag 'TT' %>

  <style type="text/css">
    #progress_bar {
      background-color: <%= hex_to_rgba(current_user ? current_user.color : User::DEFAULT_COLOR) %>;
    }
  </style>
<% end %>

<div id="overlay" style="display: none"></div>
<div id="progress_bar"></div>
<div id="timer" class="fixed_center" style="display: none">
  <div class="controls clearfix">
    <div id="ticking_sound_switch_container">
      <%= check_box_tag('ticking_sound_switch', '1', current_user ? current_user.ticking : User::DEFAULT_TICKING, id: 'ticking_sound_switch') %>
      <label for="ticking_sound_switch"><%= t('timer.ticking_sound') %></label>
    </div>
    <div class="volume">
      <div class="btn btn-default btn-sm down">
        <i class="fa fa-minus" aria-hidden="true"></i>
      </div>
      <div id="volume_icon" class="mute_toggle"></div>
      <div class="btn btn-default btn-sm up">
        <i class="fa fa-plus" aria-hidden="true"></i>
      </div>
    </div>
  </div>
  <div id="timer_counter"></div>
  <%= link_to t('timer.reset'), '#', id: 'reset', class: 'btn btn-default' %>
  <p id="reset_hint" class="help-block"><%= t('timer.or_press_esc') %></p>
</div>
<div id="new_tomato_form" class="fixed_center" style="display: none">
  <% if current_user %>
    <%= render 'tomatoes/form', remote: true %>
  <% else %>
    <div id="tomato_signin">
      <p><%= t('timer.signin_to_start_tracking') %></p>

      <%= link_to signin_path(Authorization::PROVIDER_GITHUB), method: :post, class: 'btn btn-block btn-social btn-github' do %>
        <span class="fa fa-github"></span> <%= t('signin_with.github') %>
      <% end %>

      <%= link_to signin_path(Authorization::PROVIDER_TWITTER), method: :post, class: 'btn btn-block btn-social btn-twitter' do %>
        <span class="fa fa-twitter"></span> <%= t('signin_with.twitter') %>
      <% end %>

      <div id="cancel">
        <%= link_to t('timer.cancel'), '#', id: 'reset_signin', class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

<div id="start_container" class="center-block">
  <%= link_to t('timer.start'), '#', id: 'start', class: 'btn btn-default btn-lg' %>
  <p id="start_hint" class="help-block"><%= t('timer.or_press_space') %></p>
</div>

app/views/welcome/_user_statistics.html.erb
<ul class="list-group">
  <% @tomatoes_count.each do |time_period, tomatoes_count| %>
    <li class="list-group-item">
      <span class="badge"><%= tomatoes_count %></span>
      <%= t("welcome.counters.#{time_period}") %>
    </li>
  <% end %>
</ul>

app/views/welcome/colors.html.erb
<div class="container">
  <% @colors.each do |color| %>
    <div style="width: 64px; margin: 10px; float: left;">
      <div><%= color %></div>
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 168.5 183.8">
        <rect width="100%" height="100%" fill="<%= color %>"></rect>
      </svg>
    </div>
  <% end %>

  <div style="overflow: hidden; clear: both"></div>

  <% @fluo_colors.each do |colors| %>
    <%= render partial: 'welcome/colors/tomatoes_fluo', locals: colors %>
  <% end %>

  <div style="overflow: hidden; clear: both"></div>

  <% @tshirt_colors.each do |colors| %>
    <%= render partial: 'welcome/colors/tomatoes_one_color', locals: colors %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<% unless current_user %>
  <div class="container">
    <div class="intro jumbotron">
      <p>
        <%= t('welcome.title_html') %><br/>
        <%= t('welcome.sub_title_html') %>
      </p>
    </div>
  </div>
<% end %>

<%= render partial: 'tomatoes_timer' %>

<div class="container">
  <% if current_user %>
    <%= render partial: 'dashboard' %>
  <% else %>
    <div class="intro">
      <p>
        <%= link_to signin_path(Authorization::PROVIDER_GITHUB), method: :post, class: 'btn btn-lg btn-social btn-github' do %>
          <span class="fa fa-github"></span> <%= t('signin_with.github') %>
        <% end %>

        <%= link_to signin_path(Authorization::PROVIDER_TWITTER), method: :post, class: 'btn btn-lg btn-social btn-twitter' do %>
          <span class="fa fa-twitter"></span> <%= t('signin_with.twitter') %>
        <% end %>
      </p>

      <p><%= t('timer.signin_to_start_tracking') %></p>
    </div>
  <% end %>
</div>

app/views/welcome/logo.html.erb
<div class="container">
  <% @permutations.each do |background, leaf, body| %>
    <div style="width: 64px; margin: 10px; float: left;">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 168.5 183.8">
      <rect width="100%" height="100%" fill="<%= background %>"></rect>
      <g transform="translate(-329 -504.9)">
      	<path fill="<%= leaf %>" d="M450.6,529.8c-14.7-7.7-31.7-10.9-48.6-8.7c-0.6,0.1-1.2,0.1-1.8,0.3c-0.8,0.1-1.6,0.3-2.4,0.4
      		c-6,1.1-12,2.8-17.8,5.3c-0.1,0.1-0.2,0.1-0.3,0.1c-1.9-4.9-6.3-9.5-12-12l9.3,13.3c-4.2,2-8.2,4.3-11.8,6.8
      		c-1,0.7-1.9,1.4-2.9,2.1c-0.8,0.6-1.6,1.2-2.3,1.8c-13,10.6-22.2,24.7-26.8,40.4c6-1.1,12-2.8,17.8-5.3
      		c5.5-2.4,10.6-5.2,15.3-8.6c2.4,7.5,5.9,14.6,10.3,21c7.8-7.5,14.3-16.5,18.7-26.6c10.3,3,20.9,3.9,31.4,2.9
      		c-1.8-6.8-4.6-13.5-8.2-19.7c5.9-1.1,11.7-2.8,17.4-5.3C441.2,535.7,446,532.9,450.6,529.8z"/>
      	<path fill="<%= leaf %>" d="M379.7,536.1c-3.6,0-7-2.2-8.4-5.7c-1.1-2.8-4-5.7-7.4-7.2c-4.5-2-6.5-7.4-4.4-11.8
      		c2-4.5,7.4-6.5,11.8-4.4c7.6,3.5,13.8,9.8,16.6,17c1.8,4.6-0.5,9.8-5.1,11.6C381.8,535.9,380.7,536.1,379.7,536.1z"/>
      	<path fill="<%= body %>" d="M413.3,688.7c-18.2,0-36.1-5.9-51-17.2c-11.4-8.7-20.5-20.4-26.1-33.6c-4.1-9.7-6.4-19.9-6.7-30.3
      		c-0.1-2.2-0.1-4.4,0.1-6.7c0.3-4.9,4.5-8.7,9.4-8.5c4.9,0.3,8.7,4.5,8.5,9.4c-0.1,1.8-0.1,3.5-0.1,5.2c0.3,8.2,2,16.2,5.3,23.9
      		c4.5,10.4,11.5,19.5,20.5,26.4c18.8,14.4,44.1,17.6,65.9,8.3c22.6-9.7,37.9-30.8,39.8-55.4c0.9-10.5-0.9-21.2-5.1-31
      		c-3.7-8.7-9.1-16.4-16-22.8l-1.1-0.9c-3.7-3.3-4-8.9-0.7-12.6c3.3-3.7,8.9-4,12.6-0.7l1.1,1l0.1,0.1
      		c8.9,8.1,15.8,17.8,20.5,28.9c5.3,12.4,7.6,26,6.4,39.4c-2.5,31.2-21.9,58.1-50.6,70.4C435.5,686.5,424.3,688.7,413.3,688.7z"/>
      	<path fill="<%= body %>" d="M413.5,634.9c-1.8,0-3.6-0.5-5.1-1.6l-31.2-21.6c-4.1-2.8-5.1-8.4-2.2-12.4c2.8-4.1,8.4-5.1,12.4-2.2
      		l23.9,16.5l27.6-39.9c2.8-4.1,8.4-5.1,12.4-2.2c4.1,2.8,5.1,8.4,2.2,12.4l-32.7,47.2c-1.4,2-3.4,3.3-5.8,3.7
      		C414.6,634.8,414.1,634.9,413.5,634.9z"/>
      </g>
      </svg>
    </div>
  <% end %>
</div>