config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resource :session, only: %i[create destroy]
    resource :user, only: %i[show update]
    resources :tomatoes, only: %i[index show create update destroy]
    resources :projects, only: %i[index show create update destroy]

    namespace :leaderboard do
      resource :daily, only: :show
      resource :weekly, only: :show
      resource :monthly, only: :show
      resource :overall, only: :show
    end
  end

  resources :tags, only: :index
  get '/tags/*id', to: 'tags#show', format: false, as: :tag

  resources :projects

  resources :statistics, only: :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  namespace :leaderboard do
    resource :daily, only: :show
    resource :weekly, only: :show
    resource :monthly, only: :show
    resource :overall, only: :show
  end

  resources :tomatoes

  resources :users, only: %i[show edit update destroy] do
    resources :tomatoes, only: [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin/:provider' => 'sessions#new', as: :signin
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/auth/failure' => 'sessions#failure'

  root to: 'welcome#index'

end

app/models/api/presenter/project.rb
module Api
  module Presenter
    class Project
      def initialize(project)
        @project = project
      end

      def as_json(_options = {})
        {
          id: @project.id.to_s,
          created_at: @project.created_at,
          updated_at: @project.updated_at,
          tags: @project.tags || [],
          name: @project.name,
          money_budget: @project.money_budget,
          time_budget: @project.time_budget
        }
      end
    end
  end
end

app/models/api/presenter/projects.rb
module Api
  module Presenter
    class Projects
      def initialize(projects)
        @projects = projects
      end

      def as_json(_options = {})
        {
          projects: @projects.map(&Api::Presenter::Project.method(:new)),
          pagination: {
            current_page: @projects.current_page,
            total_pages: @projects.total_pages,
            total_count: @projects.total_count
          }
        }
      end
    end
  end
end

app/models/project.rb
require 'mongoid_tags'

class Project
  include Mongoid::Document
  include Mongoid::Document::Taggable
  include Mongoid::Timestamps
  include Workable

  field :name,         type: String
  field :money_budget, type: Integer
  field :time_budget,  type: Integer

  belongs_to :user, optional: true

  validates :name, presence: true
  validates :money_budget, numericality: { greater_than: 0, allow_blank: true }
  validates :time_budget, numericality: { greater_than: 0, allow_blank: true }

  def estimated_work_time
    (time_budget.to_i * 60 * 60 * Workable::WORK_TIME_FACTOR if time_budget).to_i
  end

  def estimated_hourly_rate
    money_budget.to_f / (estimated_work_time / 60 / 60).to_f if money_budget && estimated_work_time
  end

  def tomatoes
    user.tomatoes.tagged_with(tags)
  end

  def effective_hourly_rate
    money_budget.to_f / (effective_work_time * 60 * 60).to_f if money_budget
  end

  def hourly_rate_delta
    effective_hourly_rate.to_f - estimated_hourly_rate.to_f
  end

  def work_time_delta
    effective_work_time - estimated_work_time
  end
end

app/controllers/api/projects_controller.rb
module Api
  class ProjectsController < BaseController
    include ProjectsParams

    before_action :authenticate_user!
    before_action :find_project, only: %i[show update destroy]

    # GET /api/projects
    def index
      @projects = current_user.projects
      @projects = @projects.tagged_with(params[:tag_list].split(',').map(&:strip)) if params[:tag_list]
      @projects = @projects.order_by([%i[created_at desc], %i[_id desc]]).page params[:page]

      render json: Presenter::Projects.new(@projects)
    end

    # GET /api/projects/1
    def show
      render json: Presenter::Project.new(@project)
    end

    # POST /api/projects
    def create
      @project = current_user.projects.build(resource_params)

      if @project.save
        render status: :created, json: Presenter::Project.new(@project), location: api_project_url(@project)
      else
        render status: :unprocessable_entity, json: @project.errors
      end
    end

    # POST /api/projects
    def update
      if @project.update_attributes(resource_params)
        render json: Presenter::Project.new(@project), location: api_project_url(@project)
      else
        render status: :unprocessable_entity, json: @project.errors
      end
    end

    # DELETE /api/projects/1
    def destroy
      @project.destroy

      head :no_content
    end

    private

    def find_project
      @project = current_user.projects.find(params[:id])
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsParams

  before_action :authenticate_user!
  before_action :find_project, only: %i[show edit update destroy]

  # GET /projects
  def index
    @projects = current_user.projects.order_by([%i[created_at desc]]).page params[:page]
  end

  # GET /projects/1
  def show; end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  def create
    @project = current_user.projects.build(resource_params)

    if @project.save
      redirect_to @project, notice: I18n.t('project.created')
    else
      render action: 'new'
    end
  end

  # PUT /projects/1
  def update
    if @project.update_attributes(resource_params)
      redirect_to @project, notice: I18n.t('project.updated')
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy

    redirect_to projects_url
  end

  protected

  def find_project
    @project = current_user.projects.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= bootstrap_form_for @project, layout: :horizontal do |f| %>
  <%= f.alert_message t('form_alert_message') %>

  <%= f.text_field :name, placeholder: 'Butter cookies' %>
  <%= f.text_field :tag_list, placeholder: 'cookie, butter' %>
  <%= f.number_field :money_budget, placeholder: '10', prepend: current_user.currency_unit %></p>
  <%= f.number_field :time_budget, placeholder: '1' %>
  <%= f.submit %>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <td class="project_name">
    <%= link_to project.name, project %>
  </td>
  <td><%= link_tags(project.tags) %></td>
</tr>

app/views/projects/edit.html.erb
<h1><%= t('project.edit') %></h1>

<%= render 'form' %>

<%= link_to t('show'), @project %> |
<%= link_to t('back'), projects_path %>

app/views/projects/index.html.erb
<h1><%= Project.model_name.human(count: 0) %></h1>

<% if @projects.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('mongoid.attributes.project.name') %></th>
        <th><%= t('mongoid.attributes.project.tags') %></th>
        <th><%= t('mongoid.attributes.project.money_budget') %></th>
        <th><%= t('mongoid.attributes.project.time_budget') %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= link_tags(project.tags) %></td>
        <td><%= money(project.money_budget, project.user.currency_unit) %></td>
        <td><%= distance_of_time_in_words(project.time_budget*60*60) if project.time_budget %></td>
        <td><%= link_to t('show'), project %></td>
        <td><%= link_to t('edit'), edit_project_path(project) %></td>
        <td><%= link_to t('destroy'), project, method: :delete, data: { confirm: t('are_you_sure') } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= paginate @projects %>
<% else %>
  <p><%= t('project.empty') %></p>
<% end %>

<p>
  <%= link_to t('project.new'), new_project_path, class: 'btn btn-default' %>
</p>

app/views/projects/new.html.erb
<h1><%= t('project.new') %></h1>

<%= render 'form' %>

<%= link_to t('back'), projects_path %>

app/views/projects/show.html.erb
<h1><%= @project.name %> <%= @project.model_name.human.downcase %></h1>

<dl class="dl-horizontal">
  <dt><%= t('mongoid.attributes.project.tags') %></dt>
  <dd><%= link_tags(@project.tags) %></dd>
  <dt><%= t('project.tracked_tomatoes') %></dt>
  <dd><%= @project.tomatoes.size %> <%= Tomato.model_name.human(count: @project.tomatoes.size).downcase %></dd>
  <dt><%= t('mongoid.attributes.project.money_budget') %></dt>
  <dd><%= @project.money_budget ? money(@project.money_budget, @project.user.currency_unit) : 'n/a' %></dd>
  <dt><%= t('mongoid.attributes.project.time_budget') %></dt>
  <dd><%= @project.time_budget ? distance_of_time_in_words(@project.time_budget*60*60) : 'n/a' %></dd>
</dl>

<h3>Project statistics</h3>

<dl class="dl-horizontal">
  <dt>Estimated hourly rate</dt>
  <dd><%= @project.estimated_hourly_rate ? hourly_rate(@project.estimated_hourly_rate, @project.user.currency) : 'n/a' %></dd>
  <dt>Effective hourly rate</dt>
  <dd><%= @project.effective_hourly_rate ? hourly_rate(@project.effective_hourly_rate, @project.user.currency) : 'n/a' %></dd>
  <dt>Effective/estimated hourly rate</dt>
  <dd><%= @project.hourly_rate_delta ? hourly_rate(@project.hourly_rate_delta, @project.user.currency) : 'n/a' %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>Estimated work time</dt>
  <dd><%= @project.estimated_work_time ? distance_of_time_in_words(@project.estimated_work_time) : 'n/a' %></dd>
  <dt>Effective work time</dt>
  <dd><%= distance_of_time_in_words(@project.effective_work_time) %></dd>
  <dt>Effective/estimated work time</dt>
  <dd><%= @project.work_time_delta > 0 ? '+' : '-' %> <%= distance_of_time_in_words(@project.work_time_delta.abs) %></dd>
</dl>

<%= link_to t('edit'), edit_project_path(@project) %> |
<%= link_to t('back'), projects_path %>